title: Dinacon Bali 2025 Master Index
description: Archive and documentation hub for projects created during Dinacon Bali 2025
author: Vincent Naples (@drmbt)
url: "https://drmbt.github.io"
baseurl: "/dinacon-bali-2025"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include files and directories
include:
  - thumbnails

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page" 